name: CI/CD with Terraform
on:
    push:
        branches:
            - Complete-CI/CD-with-Terraform-AWS

jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
            terraform_wrapper: false

      - name: Terraform init
        id: init
        run: terraform init -backend-config="bucket=parn-ex.project-bucket" -backend-config="region=ap-southeast-2"
        working-directory: ./terraform

      - name: Terraform Plan
        run: |
          terraform plan `
            -var="region=ap-southeast-2" `
            -var="public_key=$env:PUBLIC_SSH_KEY" `
            -var="private_key=$env:PRIVATE_SSH_KEY" `
            -var="key_name=deployer-key" `
            -out=PLAN
        working-directory: ./terraform
      

      - name: Terraform Apply
        id: apply
        run: terraform apply PLAN
        working-directory: ./terraform
env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SSH_KEY_PRIVATE: ${{ secrets.AWS_SSH_KEY_PRIVATE }}
        AWS_SSH_KEY_PUBLIC: ${{ secrets.AWS_SSH_KEY_PUBLIC }}
        AWS_TF_STATE_BUCKET_NAME: ${{ secrets.AWS_TF_STATE_BUCKET_NAME }}
        AWS_REGION: ap-southeast-2